#+TITLE: Project Metarosetta Emacs Package

* The Metalanguage
The metalanguage specification and parser.

** The Specification

** The Expression
An entity defining a particular expression. Using the metalanguage syntax as input, it constructs all underlying logic to parse textual input and structures to map semantic information to machine-readable output.

Designed as an inherently recursive fractal object.

*** Properties
All the properties contained within the expression object. These are of course defined as slots.

**** Definition
The metalanguage-specified definition of the expression in context.

This is stored as a quoted lisp list.

#+BEGIN_SRC emacs-lisp
(mldefinition
 :initarg :mldefinition
 :initform (error "Cannot create an expression without a definition!")
 :type list
 :documentation "The metalanguage-specified definition of the expression in context."
 :reader mrosetta-mldefinition)
#+END_SRC
**** Expression Type
Specifies the exact type of the expression in context.

The property itself is a ~symbol~ indicating the type of the expression.

#+BEGIN_SRC emacs-lisp
(extype
 :type symbol
 :documentation "A symbol specifying the type of the encompassing expression instance. Can be either a :quote, :context, :word or :fractal."
 :reader mrosetta-extype)
#+END_SRC

The following are the possible expression types:

***** Static Quote
Denotes the simplest expression defining statically quoted text which matches itself within any passed input.

The quote expression type is specified as a ~:quote~.
***** Variable Context
Defines variable context consisting of semantically insignificant text. While this text is unimportant for structured semantics, it remains an intrinsic part of the human-readable form.

These expressions are key in the ability to regenerate the human-readable text with updated semantic information from a machine-generated source. This enables true two-way trans-operability between the human and machine forms.

This type of expression is specified as ~:context~.
***** Matching Word
An expression matching semantically significant information.

A word expression is specified as a ~:word~.
***** Fractal
These are complex expressions consisting of one or more expressions within. Unless the entirety of the input text can be described with a single word expression, the /root/ expression is always a fractal.

In addition, fractals *never* have end values, but can have keys assigned to them matching the fractal-subtree structure contained within.

Such an expression is specified as a ~:fractal~.
**** Fractals
All the fractal elements existing within the encompassing expression instance. Only fractal expression types can contain fractals themselves.

The property itself is a list of ~mrosetta-expression~ instances.

#+BEGIN_SRC emacs-lisp
(fractals
 :initform '()
 :type list
 :documentation "A list of mrosetta-expression instances contained within the encompassing expression instance."
 :reader mrosetta-fractals)
#+END_SRC
**** Regular Expression Properties
This section contains all the properties pertaining to the encompassing expression's regex, its group keys and resulting matches of the current input, if processed.

***** Regex Keychain
In order to properly parse and distribute regex matches across the fractal expression tree, each expression object needs to have a number identifier unique to the encompassing tree.

To manage this, each tree has a single /keychain/ instance shared across all expression objects within a single fractal tree.

#+BEGIN_SRC emacs-lisp
(rkeychain
 :initarg :rkeychain
 :initform (mrosetta-keychain)
 :type mrosetta-keychain
 :documentation "The regex keychain instance managing keys for the encompassing expression tree."
 :reader mrosetta-rkeychain)
#+END_SRC

****** The Keychain
Key management is encapsulated within a simple keychain class which holds all generated keys, their respective assignments and is of course capable of generating keys unique within a single instance of the keychain object.

******* Class Definition
The class itself is designed as a no-argument constructor as the key generator is automatically initialized upon creation.

#+BEGIN_SRC emacs-lisp
(defclass mrosetta-keychain ()
  ((lastkey
    :initform '0
    :type number
    :documentation "The last key generated and assigned to a group within the context of a single instance."
    :reader mrosetta-lastkey)
   (keys
    :initform '()
    :type list
    :documentation "A property list containing all the generated keys and corresponding references of respectively assigned objects."
    :reader mrosetta-keys))
  "A regex group key generator and manager.")
#+END_SRC
******* Behavior
This section covers all defined behavior for the keychain class.

******** Generate Key
Register for a new key with a particular expression instance.

#+BEGIN_SRC emacs-lisp
(cl-defmethod mrosetta-generate-rkey ((keychain mrosetta-keychain) mlexpression)
  "Register for a new key with a particular expression instance within a provided keychain."
  (let ((key (+ 1 (slot-value keychain 'lastkey))))
    (setf (slot-value keychain 'keys) (plist-put (slot-value keychain 'keys) key mlexpression))
    (setf (slot-value keychain 'lastkey) key)))
#+END_SRC
***** Regex Key
The regex group key awarded to the encompassing expression instance.

#+BEGIN_SRC emacs-lisp
(rkey
 :type number
 :documentation "The regex matching group key for the encompassing expression instance."
 :reader mrosetta-rkey)
#+END_SRC
***** Regular Expression
The compiled regular expression of the expression in context.

This is the regex used under the hood when parsing through human-readable input.

#+BEGIN_SRC emacs-lisp
(regex
 :type string
 :documentation "The compiled regular expression of the expression in context."
 :reader mrosetta-regex)
#+END_SRC
***** Regex Match
If input is processed, this property contains the regular expression match for the encompassing expression instance.

The match is in raw text form.

#+BEGIN_SRC emacs-lisp
(rmatch
 :type string
 :documentation "The textual match of the encompassing expression within the currently set input."
 :reader mrosetta-rmatch)
#+END_SRC
**** Key
The property key to which the expression output value is assigned, if the expression itself is denoted as such.

#+BEGIN_SRC emacs-lisp
(key
 :type string
 :documentation "The property key to which the expression output value is assigned, if any."
 :reader mrosetta-key)
#+END_SRC
**** Value
If the encompassing expression instance outputs an end value, this property contains the value within the currently set input text.

The property itself is either a string representation of the singular value, or a list of matched values, if the expression is marked as plural.

#+BEGIN_SRC emacs-lisp
(value
 :type (or string list)
 :documentation "The output value matching the encompassing expression instance within the currently set input."
 :reader mrosetta-value)
#+END_SRC
**** Specifier Properties
***** Uppercase
***** Capitalized
***** Content
**** Modifier Properties
***** Uppercase
***** Lowercase
**** Plurality
**** Optionality
**** Assignment
*** Class Definition
The /expression/ class is defined as a standard EIEIO class.

#+BEGIN_SRC emacs-lisp
(defclass mrosetta-expression ()
  (())
  "The Metarosetta Expression object used to define a contextual translational expression for semantic processing.")
#+END_SRC
* Contexts
** Org
* Connectors
** Coda
